- board: seeeduino_xiao_ble
  shield: totem_left
  cmake-args: -DZMK_EXTRA_MODULES='${GITHUB_WORKSPACE}/modules/GEIGEIGEIST-zmk-config-totem'
  module_repos:
    - org: GEIGEIGEIST
      repo: zmk-config-totem
      branch: master
- board: seeeduino_xiao_ble
  shield: totem_right
  cmake-args: -DZMK_EXTRA_MODULES='${GITHUB_WORKSPACE}/modules/GEIGEIGEIST-zmk-config-totem'
  module_repos:
    - org: GEIGEIGEIST
      repo: zmk-config-totem
      branch: master
